### ISSUE TITLE
Parameter oldValue has zero value

### ISSUE THREAD

**Issue by tinxx** [CodeDead/PK-Finder#1]
Hello, I was trying to backup my Windows 10 product key to be able to reinstall it if needed but I always get this error. I tried it with versions 1.5 and 1.4.2.

<img width="277" alt="pk_error" src="https://user-images.githubusercontent.com/13608545/45372560-9ebf1680-b5ed-11e8-9c92-67bd1038b58b.png">

> The character string cannot have zero length.
> Parameter name: oldValue

**Comment by CodeDead** [comment]
Hi,

This can happen if your Windows 10 is not activated or if your user requires administrative rights. Try executing the software with administrator rights. In case your Windows is not activated: this software is intended for activated versions of Windows only. No support is given for hacking Windows. If this is not the case, feel free to send an email over at admin(at)codedead.com for further support (because we'll ask for a bit of sensitive info which should not be posted online) or reply below 👍 .

https://github.com/CodeDead/PK-Finder/blob/master/PK%20Finder/Classes/KeyManager.cs#L67

Edit:
This can also happen if your registry is corrupted because it's missing the following key or it has been modified with corrupt data:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion` -> `DigitalProductId` (_REG_BINARY_)

Kind regards

**Comment by tinxx** [comment]
Yes, I obviously tried to hack Windows. Thanks for the implication.

It could be possible that it was not activated at the time I tried to extract the license code because the computer was brand new and I was backing up the key prior wiping it for reinstallation.

**Comment by CodeDead** [comment]
You'd be surprised how many messages we get with this error message. Don't take it as an implication personally. It is, however, an issue if you notice this error message on a Genuin Windows (Activated).

Please do test it on a machine that is activated using a valid product key before running the application. If the error still persists, we'd need to ask you for some system info (preferably via mail as this is sensitive information). (command `systeminfo`)

**Comment by tinxx** [comment]
Machine is actually activated.
Windows 10 Pro, 64-bit, version 1709 build 16299.371.

**Comment by CodeDead** [comment]
@tinxx Could you email us the output when you run the `systeminfo` command in powershell or CMD?
Don't post it here, it contains data that should not be public. You can always email it to us.

**Comment by tinxx** [comment]
Sorry to get back to you so late. I have no access to the instance anymore so that I am unable to extract the data you requested.

**Comment by CodeDead** [comment]
No problem @tinxx , feel free to reopen the issue whenever you encounter this issue again!
