### ISSUE TITLE
Parameter oldValue has zero value

### ISSUE THREAD

**Issue by julianhille** [CodeDead/PK-Finder#4]
Windows Server 2022 does show me this warning.
System is valid and activated.
I installed it completely new on a spare hard drive, as the other installation went bonkers.
I'm unable to find my piece of paper so i tried it with this software. slmgr -dlvi shows me on the bonkers installation everythings fine.

Is there anything else i can supply to get the key?

i am running the software as administrator and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> DigitalProductId is missing from the registry.

It is OEM_COA Channel or OEM:NONSLP channel but i definitely had a DVD with a license sticker

**Comment by CodeDead** [comment]
Hi Julian,

Thanks for reaching out. Are you aware of any Windows Registry corruption?
In any case, it's always a good idea to perform some of the basic recovery
steps to make sure that your Windows installation is working as intended:
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/repair-a-windows-image?view=windows-11

Kind regards

**Comment by CodeDead** [comment]
Duplicate of https://github.com/CodeDead/PK-Finder/issues/1

**Comment by julianhille** [comment]
i recovered the disk from install day 1 even there this is missing.

**Comment by CodeDead** [comment]
You do need a valid and activated installation in order to use this application. It will not recover 'unregistered' license keys.
If your current Windows installation is not activated, PK Finder will not be able to retrieve a license key, because there isn't one present.

**Comment by julianhille** [comment]
The current system is fully activated as stated before thats what confuses me i just checked with slmgr /dlv and slmgr dli
it even tells me "part" of the license key (last letters / digits) which i remember to be correct

**Comment by CodeDead** [comment]
Your key might be embedded in the UEFI. This PowerShell command might be able to extract it from your UEFI, if present:

```PowerShell
(Get-WmiObject -query 'select * from SoftwareLicensingService').OA3xOriginalProductKey
```

If it is not present there either, I am afraid that we can't offer any other way to extract the license information.

**Comment by julianhille** [comment]
tried that before. it just prints OA3xOriginalProductKey and then an empty line and that would be only for pre installed oem versoins as far as i remember / understood.

**Comment by julianhille** [comment]
i feel like its a server 2022 issue maybe its to new and maybe it handles things differently.

**Comment by julianhille** [comment]
just started slmgr /ato which should register and now i got the DigitalProductId in the registry, but still get the same error

**Comment by CodeDead** [comment]
> i feel like its a server 2022 issue maybe its to new and maybe it handles things differently.

That would be odd because I just tested it on 2022 edition and it should work fine. You might be able to find support from Microsoft themselves if need be (but do note that you should not have messed with the kms settings):
https://support.serviceshub.microsoft.com/

Perhaps the solution is just a reboot away, but either way, it would be better to ask Microsoft directly to extract your license key if all else fails, since you still paid for it.

If something were to change within the way Windows handles digital product ID registration, then I can update the application to reflect on those changes, but as it stands, it still extracts license keys, even on Server 2022. Please do make sure you have an internet connection on the machine in question to make sure Windows is truly activated in online mode, and reboot your machine at least once after activation of your machine.

**Comment by CodeDead** [comment]
> just started slmgr /ato which should register and now i got the DigitalProductId in the registry, but still get the same error

Make sure to reboot your device after online activation as well, let me know if that works.

**Comment by julianhille** [comment]
ok just a last note until we might close. i used now a powershell tool to decrypt the DigitalProductId4 which looks okayish. 

it hast internet and i rebooted at least ten times in the last hours as im migrating the thing. will do again and will test the key on the second installation

**Comment by julianhille** [comment]
btw. when i decrypt DigitalProductId it states the key is somewhat like BBBB-BBBBB-BBBBB etc

**Comment by CodeDead** [comment]
> btw. when i decrypt DigitalProductId it states the key is somewhat like BBBB-BBBBB-BBBBB etc

Seems about right.

**Comment by julianhille** [comment]
these two keys do not work.i guess i need to find that sticker somewhere or get help from ms

**Comment by julianhille** [comment]
thanks for your help. if i get some infos from ms i will report back to you

**Comment by CodeDead** [comment]
You too. Sorry I can't be of more help but the cause is absolutely eluded to me since this problem is like finding a needle in a haystack that you can only find if you have the entire haystack in front of you (which I don't, and I don't have the time or resources to support you remotely as an unpaid FOSS developer unfortunately).

If you find the cause, let me know and I might be able to add a dialog message for users who are facing the same issue (although we only have had one other report of this issue - e.g. #1). I will never be able to extract license keys where the information is simply missing, but if we know what causes it to be missing, we could warn the user about it.
